/***************************************************************
 * Copyright (C) 2013
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ***************************************************************/

/* FILE NAME   : TLR.H
 * PURPOSE     : Tough Light Racing project.
 *               Main declaration module.
 * PROGRAMMER  : CGSG'2013.
 *               Maria Abramova,
 *               Vasiliy Cheptsov,
 *               Nikita Gaevoy,
 *               Aleksandra Gorskaya,
 *               Stanislav Petrov,
 *               Vsevolod Poletaev,
 *               Vyacheslav Rusanov,
 *               Leonid Voroshilov,
 *               Tatyana Sankova,
 *               Vitaly A. Galinsky.
 * LAST UPDATE : 03.08.2013
 * NOTE        : Namespace 'tlr'.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum
 */

#ifndef __TLR_H_
#define __TLR_H_

#include "anim/win/win.h"
#include "anim/timer.h"
#include "anim/rnd/shader.h"
#include "anim/rnd/image.h"
#include "anim/rnd/mtl.h"
#include "anim/rnd/prim.h"
#include "anim/rnd/render.h"
#include "anim/input.h"
#include "anim/anim.h"
#include "gp/map.h"
#include "gp/server.h"
#include "gp/checkgp.h"
#include "gp/client.h"
#include "3d/player.h"
#include "units/units.h"

#endif /* __TLR_H_ */

/* END OF 'TLR.H' FILE */
