/***************************************************************
 * Copyright (C) 2013
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ***************************************************************/

/* FILE NAME   : MTH.H
 * PURPOSE     : Tough Light Racing project.
 *               Mathemathic support header file.
 *               Main math support declaration module.
 * PROGRAMMER  : CGSG'2013.
 *               Leonid Voroshilov
 * LAST UPDATE : 03.08.2013
 * NOTE        : Namespace 'tlr'.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum
 */

#ifndef __MTH_H_
#define __MTH_H_

#include "vec2.h"
#include "vec.h"
#include "matr.h"
#include "color.h"

#endif /* __MTH_H_ */

/* End of 'MTH.H' function */
